name: Docker Image python fast api

on:
  push:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image 
      run: |
         docker build . -t pythontestrepo.azurecr.io/python-test:${{ github.sha }}
         docker images
         
    - uses: azure/docker-login@v1
      with:
        login-server: myrepo1.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push docker image to ACR repo.
      run: |
         docker push pythontestrepo.azurecr.io/python-test:${{ github.sha }} 
   
    
      
