name: Docker Image python fast api

on:
  push:
    branches: 
      - main
      
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image 
      run: |
         docker build . -t pythontestrepo.azurecr.io/python-test:latest1
         docker images
         
    - uses: azure/docker-login@v1
      with:
        login-server: pythontestrepo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push docker image to ACR repo.
      run: |
          docker push pythontestrepo.azurecr.io/python-test:latest1

  Deploy:
   needs: build
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: 'Az CLI Login'
      uses: azure/login@v2
      with:
         CLIENT_ID: ${{secrets.CLIENT_ID}}
         CLIENT_SECRECT: ${{secrets.CLIENT_SECRECT}}
         SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
         TENANT_ID: ${{secrets.TENANT_ID}}

    - name: Set AKS account
      run: |
       az account set --subscription ${{ secrets.SUBSCRIPTION }}
       az aks get-credentials --resource-group python-test-rg --name kubernetes-test-env
    
    - name: Deploy to AKS Cluster
      run: |
          pwd 
          kubectl apply -f deployment.yml 
          kubectl get pods
          kubectl get svc
          sleep 1m
          kubectl get svc
    - name: deploy the app
      run: |
         echo 'Application is deployed'
