name: terraform infra provisiong

on:
  push:
    branches: 
      - infra

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
       ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
       ARM_CLIENT_SECRECT: ${{secrets.ARM_CLIENT_SECRECT}}
       ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
       ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  
    - name: 'Setup terraform'
      uses: hashicorp/setup-terraform@v1
      
    - name: 'Terraform Init'
      run: terraform init
 
    - name: 'Terraform Plan'
      run: terraform plan
      
