name: terraform infra provisiong

on:
  pull_request:
    branches: 
      - infra
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: 'test repo'
      run: |
       echo " This is for test"
       

    
