name: terraform infra provisiong

on:
  push:
    branches: 
      - infra
      
permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRECT: ${{secrets.CLIENT_SECRECT}}
      SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      TENANT_ID: ${{secrets.TENANT_ID}}
  
    
    defaults:
      run:
        shell: bash
      
    steps:
    - uses: actions/checkout@v2

    #- name: Azure Login
    #  uses: azure/login@v2
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Setup terraform'
      uses: hashicorp/setup-terraform@v1
      
    - name: 'Terraform Init'
      id: init
      run: terraform init
 
    - name: Terraform plan
      id: plan
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      run: terraform plan
      
